spring:
  application:
    name: tickets

  # Database connections
  spring:
    datasource:
      url: jdbc:postgres://localhost:5432/event-tickets
      username: tickets
      password: changeinprod!

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        dialect: org.hibernate.dialect.PostgrSQLDrialect
    keycloak:
      image: quay.io/keycloak/keycloak:latest
      ports:
        - "9090:8080"
      environment:
        KEYCLOACK_ADMIN: admin
        KEYCLOACK_ADMIN_PASSWORD: admin
      volumes:
        - keycloak-data:/opt/keycloak/data
      command:
        - start-dev
        - --db=dev-file
    security:
      oauth2.resourceserver.jwt.issuer-uri=http//localhost:9090/realms/event-ticket-platform
volumes:
  keycloak-data:
    driver: local